package com.example.krishivaanibackend.Controller;

import com.example.krishivaanibackend.dto.ApiResponse;
import com.example.krishivaanibackend.dto.QuestionRequestDTO;
import com.example.krishivaanibackend.dto.QuestionResponseDTO;
import com.example.krishivaanibackend.entity.Question;
import com.example.krishivaanibackend.service.QuestionService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/ai")
@CrossOrigin(origins = "*")
public class AiController {

    private final QuestionService questionService;
    public AiController(QuestionService questionService) {
        this.questionService = questionService;
    }

//    POST /api/v1/ai/ask - Ask a question to the AI
    // This endpoint will accept a question and return an answer generated by the AI.
    // The question will be saved in the database, and the answer will be generated using an AI model (e.g., OpenAI's GPT).
    @PostMapping("/ask")
    public ResponseEntity<ApiResponse<QuestionResponseDTO>> ask(@Valid @RequestBody QuestionRequestDTO request) {
//        1. Save Question to database
        Question saved = questionService.submitQuestion(request.getContent(), request.getLanguage());

//        2. TODO: RAG pipeline + LLM call(AI integration sprint)
        String stubAnswer = "[AI answer will appear here after AI integration sprint]";

//        3. Store stub answer in database
        Question withAnswer = questionService.updateAnswer(saved.getId(), stubAnswer);

        return ResponseEntity.status(HttpStatus.CREATED)
                .body(ApiResponse.ok(QuestionResponseDTO.from(withAnswer),"Question received"));
    }
}
